### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')

### ISSUE THREAD

**Issue by laurynas-wn** [livekit/livekit-react#30]
Hello,

We've implemented livekit in our react app and everything works on localhost, in connection-tester and in react example. However we're getting an error when trying to connect in our qa environment.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')`

I've tried to reproduce the error in sandbox, however I haven't managed to get the same error.

We've done some customization, however even with a basic setup like this we're getting the error
```
    <LiveKitRoom
        url={url}
        token={token}
        connectOptions={{
          logLevel: LogLevel.trace,
          audio: true,
          video: true,
        }}
      />
```
Component just sits there displaying 'connecting' message.

Also it seems like client connects to the server and is sending data on any sound picked up by the microphone. If we connect with a second user using react-example online, we can see the first one in the room.

QA frontend sits on http, could this be an issue? I understand you may not be able to solve the issue without a reproducible example, but any ideas would be appreciated.

```
connecting to wss://redacted.redacted/rtc?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGF1cnluYXMgUHVza3VuaWdpcyIsInZpZGVvIjp7InJvb21Kb2luIjp0cnVlLCJyb29tIjoiYWEyMDlhNmYtNmI3MS00OTc2LWJjOGYtYzRlODk5ODEzYjBmIiwicm9vbUFkbWluIjp0cnVlfSwiaWF0IjoxNjQ2MDQyMTgxLCJuYmYiOjE2NDYwNDIxODEsImV4cCI6MTY0NjA1NjU4MSwiaXNzIjoiQVBJeXdlNmlENFAzRUUzIiwic3ViIjoiZDQxOWVkNzUtZWRiMi00M2E4LTk1OTAtMWFlY2EwNTg5Nzg0IiwianRpIjoiZDQxOWVkNzUtZWRiMi00M2E4LTk1OTAtMWFlY2EwNTg5Nzg0In0.cd_-Hin1bNaJ5jncOUSx-X7xaEYh1vuWobjZufhIUfs&sdk=js&version=0.16.6&protocol=6
```

```
connected to Livekit Server 0.15.4
```

```
room event stateChanged connected
```

```
received server offer offer stable
```

```
react_devtools_backend.js:4061 got ICE candidate from peer {candidate: 'candidate:3745597892 1 udp 2130706431 redacted-ip 7882 typ host', sdpMid: '', sdpMLineIndex: 0, usernameFragment: null} 1
overrideMethod @ react_devtools_backend.js:4061
client.onTrickle @ main.fa0a68546208aea3.esm.js:2
handleSignalResponse @ main.fa0a68546208aea3.esm.js:2
(anonymous) @ main.fa0a68546208aea3.esm.js:2
(anonymous) @ main.fa0a68546208aea3.esm.js:2
i @ main.fa0a68546208aea3.esm.js:2
u.onmessage @ main.fa0a68546208aea3.esm.js:2
```
```
react_devtools_backend.js:4061 got ICE candidate from peer {candidate: 'candidate:1655846948 1 tcp 2124414975 redacted-ip 7881 typ host tcptype passive', sdpMid: '', sdpMLineIndex: 0, usernameFragment: null} 1
overrideMethod @ react_devtools_backend.js:4061
client.onTrickle @ main.fa0a68546208aea3.esm.js:2
handleSignalResponse @ main.fa0a68546208aea3.esm.js:2
(anonymous) @ main.fa0a68546208aea3.esm.js:2
(anonymous) @ main.fa0a68546208aea3.esm.js:2
i @ main.fa0a68546208aea3.esm.js:2
u.onmessage @ main.fa0a68546208aea3.esm.js:2
```

```
sending answer
```

```
react_devtools_backend.js:4061 sending ice candidate RTCIceCandidate {candidate: 'candidate:1675499713 1 udp 2113937151 efacf518-004…typ host generation 0 ufrag 04AX network-cost 999', sdpMid: '0', sdpMLineIndex: 0, foundation: '1675499713', component: 'rtp', …}
```

```
react_devtools_backend.js:4061 pc connected
overrideMethod @ react_devtools_backend.js:4061
(anonymous) @ main.fa0a68546208aea3.esm.js:2
(anonymous) @ main.fa0a68546208aea3.esm.js:2
i @ main.fa0a68546208aea3.esm.js:2
t.onconnectionstatechange @ main.fa0a68546208aea3.esm.js:2

```
**The Issue**
```
main.fa0a68546208aea3.esm.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at b.<anonymous> (main.fa0a68546208aea3.esm.js:2:5014917)
    at Object.u (main.fa0a68546208aea3.esm.js:2:4856125)
    at b.a.emit (main.fa0a68546208aea3.esm.js:2:4858172)
    at b.<anonymous> (main.fa0a68546208aea3.esm.js:2:5006293)
    at Generator.next (<anonymous>)
    at o (main.fa0a68546208aea3.esm.js:2:5000886)
```

```
room event connectionQualityChanged excellent 
Q {_events: {…}, _eventsCount: 8, _maxListeners: undefined, audioLevel: 0, isSpeaking: false, …}
audioLevel: 0
audioTracks: Map(0) {size: 0}
engine: b {_events: {…}, _eventsCount: 9, _maxListeners: undefined, rtcConfig: {…}, subscriberPrimary: true, …}
handleSubscribedQualityUpdate: e=> {…}
identity: "d419ed75-edb2-43a8-9590-1aeca0589784"
isSpeaking: false
metadata: ""
name: "My name"
onTrackMuted: (e,t)=> {…}
onTrackUnmuted: e=>{this.onTrackMuted(e,!1)}
onTrackUnpublish: e=>{this.unpublishTrack(e)}
participantInfo: {sid: 'PA_V99bdVAVz9Lm', identity: 'd419ed75-edb2-43a8-9590-1aeca0589784', state: 0, metadata: '', joinedAt: 1646042181, …}
pendingPublishing: Set(0) {size: 0}
roomOptions: {logLevel: 'trace', audio: true, video: true, adaptiveStream: undefined, audioCaptureDefaults: {…}, …}
sid: "PA_V99bdVAVz9Lm"
tracks: Map(0) {size: 0}
videoTracks: Map(0) {size: 0}
_connectionQuality: "excellent"
_events: {metadataChanged: ƒ, participantMetadataChanged: ƒ, trackMuted: ƒ, trackUnmuted: ƒ, localTrackPublished: ƒ, …}
_eventsCount: 8
_maxListeners: undefined
connectionQuality: (...)
isCameraEnabled: (...)
isMicrophoneEnabled: (...)
isScreenShareEnabled: (...)
joinedAt: (...)
lastCameraError: (...)
lastMicrophoneError: (...)
[[Prototype]]: c
```

**Comment by laurynas-wn** [comment]
The issue dissapeared in domain with https.
