### ISSUE TITLE
Exception being thrown when using react strict mode

### ISSUE THREAD

**Issue by lukasIO** [livekit/livekit-react#87]
as reported by @merazgasalim in https://github.com/livekit/livekit-react/pull/79
> I just upgraded livekit-client to v1.3.1 but still the same problem.
>
> I'm sure it's related to the double useEffect call. I just downloaded the livekit/livekit-react and made the example app in React 
> Strict Mode so the bug appears
>
> to reproduce the bug just update the App.tsx in example/src like that
> 
> ```tsx
> import '@livekit/react-components/dist/index.css';
> import { HashRouter as Router, Route, Routes } from 'react-router-dom';
> import { PreJoinPage } from './PreJoinPage';
> import { RoomPage } from './RoomPage';
> 
> import React from 'react';
> 
> const App = () => {
>   return (
> 
>   <React.StrictMode>
>     <Route path="/room" element={} />
>     <Route path="/" element={} />
>   </React.StrictMode>
>   );
> };
> export default App;
> ```
> 
> Here's also the stack Error
> ```
> Uncaught (in promise) TypeError: _b.reject is not a function at _callee85$ (Room.ts:366:1) at tryCatch (runtime.js:63:1) at Generator.invoke [as _invoke] (runtime.js:294:1) at Generator.next (runtime.js:119:1) at asyncGeneratorStep (asyncToGenerator.js:3:1) at _next (asyncToGenerator.js:25:1) at asyncToGenerator.js:32:1 at new Promise (<anonymous>) at Room.disconnect (asyncToGenerator.js:21:1) at LiveKitRoom.tsx:48:1
> ```

**Comment by lukasIO** [comment]
additional info by @merazgasalim:

>  I think that I found the issue!
> Calling disconnect() while the room state is in connecting state causes this bug
> 
> I updated the useEffect return like that and the bug is fixed
> 
> `if (roomState.room?.state === ConnectionState.Connected) { roomState.room?.disconnect(); }`

sounds like a problem that might best be fixed in the livekit-client package

**Comment by lukasIO** [comment]
@merazgasalim I opened https://github.com/livekit/livekit-react/pull/89 to fix the issue and explicitly enabled strict mode for the example app.
